version: '3.3'

# datavaultbuilder version is defined as DVB_TAG in the file '.env'

services:

  exasol:
    image: 'exasol/docker-db:7.0.2'
    volumes:
            - mydata:/exa
    ports:
      - '8563:8563'
      - '6583:6583'
      - '8888:8888'
      - '8443:443'
    privileged: true

volumes:
  mydata:
