version: '3.3'

# datavaultbuilder version is defined as DVB_TAG in the file '.env'

services:

  exasol:
    image: 'exasol/docker-db:6.2.10-d1'
    volumes:
            - exasol:/exa
    ports:
      - '6583:6583'
      - '8888:8888'
      - '8443:443'
    privileged: true

volumes:
   exasol:
